version: "3"
services:
  bot:
    build: .
    command: python main.py
    environment:
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}
      - BOT_TOKEN=${BOT_TOKEN}
      - MONGO_URI=${MONGO_URI}
      - DB_NAME=${DB_NAME}
      - CHANNEL_URL=${CHANNEL_URL}
      - ADMIN_IDS=${ADMIN_IDS}
      - AUTO_DELETE_TIME=${AUTO_DELETE_TIME}
      - INITIAL_CREDITS=${INITIAL_CREDITS}