services:
  - type: worker
    name: rihnobot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: MONGO_URI
        sync: false
      - key: DB_NAME
        value: RihnoBotDB
      - key: CHANNEL_URL
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: AUTO_DELETE_TIME
        value: 300
      - key: INITIAL_CREDITS
        value: 10